version: '2'

services:
  cassandra1:
    image: snapshot.docker.palantir.build/cassandra/sls-cassandra:3.25.1-2-g9dbee03
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - MAX_HEAP_SIZE=$CASSANDRA_MAX_HEAP_SIZE
      - HEAP_NEWSIZE=$CASSANDRA_HEAP_NEWSIZE
      - LOCAL_JMX=no

  cassandra2:
    image: snapshot.docker.palantir.build/cassandra/sls-cassandra:3.25.1-2-g9dbee03
    depends_on:
      - cassandra1
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - MAX_HEAP_SIZE=$CASSANDRA_MAX_HEAP_SIZE
      - HEAP_NEWSIZE=$CASSANDRA_HEAP_NEWSIZE
      - LOCAL_JMX=no

  cassandra3:
    image: snapshot.docker.palantir.build/cassandra/sls-cassandra:3.25.1-2-g9dbee03
    depends_on:
      - cassandra1
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - MAX_HEAP_SIZE=$CASSANDRA_MAX_HEAP_SIZE
      - HEAP_NEWSIZE=$CASSANDRA_HEAP_NEWSIZE
      - LOCAL_JMX=no

  cli:
    image: snapshot.docker.palantir.build/cassandra/sls-cassandra:3.25.1-2-g9dbee03
    depends_on:
      - cassandra1
    entrypoint: [bash, -c, '"$$@"', --]
    command: exit
